apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: minimal-app
spec:
  components:
    - name: express-server
      type: webservice
      properties:
        image: oamdev/hello-world
        imagePullPolicy: IfNotPresent
        ports:
         - port: 8000
           expose: true
      traits:
        - type: scaler
          properties:
            replicas: 1
