apiVersion: v1
data:
  00_default_overrides.xml: |
    <clickhouse>
      <!-- Macros -->
      <macros>
        <shard from_env="CLICKHOUSE_SHARD_ID"></shard>
        <replica from_env="CLICKHOUSE_REPLICA_ID"></replica>
        <layer>langfuse-clickhouse</layer>
      </macros>
      <!-- Log Level -->
      <logger>
        <level>information</level>
      </logger>
      <!-- Zookeeper configuration -->
      <zookeeper>
        <node>
          <host from_env="KEEPER_NODE_0"></host>
          <port>2181</port>
        </node>
        <node>
          <host from_env="KEEPER_NODE_1"></host>
          <port>2181</port>
        </node>
        <node>
          <host from_env="KEEPER_NODE_2"></host>
          <port>2181</port>
        </node>
      </zookeeper>
      <listen_host>0.0.0.0</listen_host>
      <listen_host>::</listen_host>
      <listen_try>1</listen_try>
      <background_schedule_pool_size>16</background_schedule_pool_size>
    </clickhouse>
kind: ConfigMap
metadata:
  name: langfuse-clickhouse
  namespace: genai
  labels:
    app.kubernetes.io/component: clickhouse
    app.kubernetes.io/instance: langfuse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/version: 25.2.1
    helm.sh/chart: clickhouse-8.0.5
